### ISSUE TITLE
Several fatal errors after removing a spool 

### ISSUE THREAD

**Issue by NeilSCGH** [dojohnso/OctoPrint-SpoolManager#46]
Hello,
Thank you for supporting this plugin 🙂

I'm using your plugin for octoprint and I encountered the following errors when doing several things as creating a new spool, downloading database etc. All of this started after I've deleted a spool in the regular spool tab.

Note : 
 - Restarting the system doesn't solve the issue
 - Deleting and re-installing the plugin without erasing data also doesn't help

Maybe it's a corrupt file ?

Here are all the logs :

```
2024-05-03 18:21:12,092 - octoprint - ERROR - Exception on /plugin/SpoolManager/downloadDatabase [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 748, in downloadDatabase
    return send_file(self._databaseManager.getDatabaseSettings().fileLocation,
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'
```

```
2024-05-03 18:16:49,432 - octoprint - ERROR - Exception on /plugin/SpoolManager/loadSpoolsByQuery [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 914, in loadAllSpoolsByQuery
    for selectedSpool in self.loadSelectedSpools()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 143, in loadSelectedSpools
    "Last selected Spool for Tool %d from plugin-settings not found in database. Maybe deleted in the meantime." % i)
NameError: name 'i' is not defined
```

```
2024-05-03 18:16:57,235 - octoprint - ERROR - Exception on /plugin/SpoolManager/saveSpool [PUT]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 988, in saveSpool
    self.checkRemainingFilament()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/__init__.py", line 81, in checkRemainingFilament
    selectedSpools = self.loadSelectedSpools()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 143, in loadSelectedSpools
    "Last selected Spool for Tool %d from plugin-settings not found in database. Maybe deleted in the meantime." % i)
NameError: name 'i' is not defined
```

```
2024-05-03 18:16:57,336 - octoprint - ERROR - Exception on /plugin/SpoolManager/loadSpoolsByQuery [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 914, in loadAllSpoolsByQuery
    for selectedSpool in self.loadSelectedSpools()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 143, in loadSelectedSpools
    "Last selected Spool for Tool %d from plugin-settings not found in database. Maybe deleted in the meantime." % i)
NameError: name 'i' is not defined
```

```
2024-05-03 18:21:42,005 - octoprint.server.api.settings - ERROR - Could not save settings for plugin SpoolManager Plugin (1.7.3)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/settings.py", line 1217, in _saveSettings
    plugin.on_settings_save(data["plugins"][plugin_id])
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/__init__.py", line 739, in on_settings_save
    selectedSpools = self.loadSelectedSpools()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_SpoolManager/api/SpoolManagerAPI.py", line 143, in loadSelectedSpools
    "Last selected Spool for Tool %d from plugin-settings not found in database. Maybe deleted in the meantime." % i)
NameError: name 'i' is not defined
```

When I try to download the database, I get the following error :
```
{
  "error": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
}
```

**Comment by NeilSCGH** [comment]
I've fixed the problem by uninstalling the plugin and it's data, and re-installing it. 
Before erasing the data I've copied the spoolmanager.db file via ssh, and after I've restored it and the plugin was still functionnal, so the issue doesnt seems to come from this file (I've opened it on my computer and it is not corrupted. 
I've made a backup before erasing data, but I dont know if your plugin has other data file elsewhere.
